- hosts: default
  become: true
  become_method: sudo
  tasks:
  - name: Check if release 10.3-RELEASE exists
    iocell: state=fetched release=10.3-RELEASE

  - name: Check if basejail exists
    iocell: state=exists tag=test_10.3-RELEASE
    ignore_errors: true

  - name: Check if base jail can be created
    iocell: state=basejail tag=test_10.3-RELEASE release=10.3-RELEASE
# Basejails can be made templates
  - name: Verify that base jail can be converted
    iocell: state=set tag=test_10.3-RELEASE properties="istemplate=yes"
  - name: Check if clone can be had
    iocell: state=cloned tag=test_jail clone_from=test_10.3-RELEASE
  - name: Check if cloned test jail can be destroyed
    iocell: state=absent tag=test_jail
  - name: Verify that base jail can be converted back
    iocell: state=set tag=test_10.3-RELEASE properties="istemplate=no"
# template glue
  - name: Check if template jail can be created
    iocell: state=template tag=test_template_10.3-RELEASE release=10.3-RELEASE
    tags:
    - debug
  - name: Check if template jail can't be started
    iocell: state=started tag=test_template_10.3-RELEASE force=yes
    ignore_errors: yes
  - name: Check if template jail can be force-started
    iocell: state=started tag=test_template_10.3-RELEASE force=yes
  - name: Check if template jail can be stopped
    iocell: state=stopped tag=test_template_10.3-RELEASE
  - name: Check if template jail can be destroyed
    iocell: state=absent tag=test_template_10.3-RELEASE

# check with an absent jail. should produce lots of ignored errors.
  - name: Check if absent jail can't be destroyed
    iocell: state=absent tag=absent
    ignore_errors: yes
  - name: Check if absent jail can't be stopped
    iocell: state=stopped tag=absent
    ignore_errors: yes
  - name: Check if absent jail can be restarted
    iocell: state=restarted tag=absent
    ignore_errors: yes
  - name: Check if absent jail can be started
    iocell: state=started tag=absent
    ignore_errors: yes

# check everything
  - name: Check if test jail can be cloned
    iocell: state=cloned clone_from=test_10.3-RELEASE tag=test_jail
  - name: Check if pkg info does not work in not-started test jail
    iocell: state=pkg tag=test_jail cmd="info"
    ignore_errors: yes
  - name: Check if test jail can be started
    iocell: state=started tag=test_jail
  - name: Check if test jail that's started -- is started
    iocell: state=started tag=test_jail
  - name: Check if exec works in test jail
    iocell: state=exec tag=test_jail cmd="/bin/ls -la /root"
  - name: Check if pkg info works in test jail
    iocell: state=pkg tag=test_jail cmd="info"
  - name: Check if test jail can be restarted
    iocell: state=restarted tag=test_jail
  - name: Check if test jail can be stopped
    iocell: state=stopped tag=test_jail
  - name: Check if test jail can be started again
    iocell: state=started tag=test_jail
  - name: Check if test jail can be destroyed
    iocell: state=absent tag=test_jail

  - name: Check if base jail can be destroyed
    iocell: state=absent tag=test_10.3-RELEASE
